# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # Link to your container registry. You will launch it in Yandex Cloud.
  repository: cr.yandex/crpekqtgdde3o6ka49eo/dds_service
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v2024-03-14-r3"

containerPort: 5000

config:
  KAFKA_HOST: "rc1d-vdhqfb9d6h7ugl8k.mdb.yandexcloud.net"
  KAFKA_PORT: "9091"
  KAFKA_CONSUMER_USERNAME: "producer_consumer"
  KAFKA_CONSUMER_PASSWORD: "RJ45_Kafka"
  KAFKA_CONSUMER_GROUP: "test-consumer1"
  KAFKA_SOURCE_TOPIC: "stg-service_orders"
  KAFKA_DESTINATION_TOPIC: "dds-service-orders"

  PG_WAREHOUSE_HOST: "rc1a-6yuyv0p3vt4vhat6.mdb.yandexcloud.net"
  PG_WAREHOUSE_PORT: "6432"
  PG_WAREHOUSE_DBNAME: "sprint9dwh"
  PG_WAREHOUSE_USER: "db_user"
  PG_WAREHOUSE_PASSWORD: "RJ45_Postgresql"

  REDIS_HOST: "c-c9q01sfb6ec5tsep5nis.rw.mdb.yandexcloud.ne"
  REDIS_PORT: "6380"
  REDIS_PASSWORD: "RJ45_Redis"


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
